[package]
name = "gameboy_emulator"
version = "0.1.0"
authors = ["Srikur Kanuparthy <srikur@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
arrayref = "0.3.6"
gl = "0.10.0"